# Generated by Django 3.1.6 on 2021-03-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
    ]
