# Generated by Django 3.1.6 on 2021-03-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0002_auto_20210316_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
    ]
