# Generated by Django 3.1.6 on 2021-03-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0003_auto_20210316_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='comment',
        ),
    ]
