# Generated by Django 3.1.7 on 2021-03-18 20:14

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('stock_floor', '0004_auto_20210316_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tgtags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
