# Generated by Django 3.1.6 on 2021-03-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0004_auto_20210313_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
