# Generated by Django 3.1.7 on 2021-03-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0005_post_tgtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
