# Generated by Django 3.1.7 on 2021-03-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0006_auto_20210319_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
