# Generated by Django 3.1.6 on 2021-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
