# Generated by Django 3.1.7 on 2021-03-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0007_remove_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
