# Generated by Django 3.1.5 on 2021-04-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0008_delete_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stock_floor.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='coverimg',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
