# Generated by Django 3.1.6 on 2021-03-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0008_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
