# Generated by Django 3.1.5 on 2021-04-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0009_auto_20210322_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coverimg',
            field=models.ImageField(default='Alphabet_Design_3.png', upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stock_floor.comment'),
        ),
    ]
