# Generated by Django 3.1.6 on 2021-03-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0009_remove_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(max_length=150),
        ),
    ]
