# Generated by Django 3.1.5 on 2021-04-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0009_auto_20210409_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
