# Generated by Django 3.1.5 on 2021-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0011_auto_20210412_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cleancontent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
