# Generated by Django 3.1.5 on 2021-04-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_floor', '0012_post_cleancontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cleancontent',
        ),
    ]
