# Generated by Django 3.1.5 on 2021-04-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='Alphabet_Icon.png', null=True, upload_to='img/profile/'),
        ),
    ]
